# Generated by Django 2.1.4 on 2018-12-10 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('introduction', models.CharField(default='', max_length=2000)),
                ('server_location', models.CharField(default='', max_length=100)),
                ('server_type', models.CharField(default='', max_length=100)),
                ('server_spec', models.CharField(default='', max_length=2000)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('proposal', models.FileField(upload_to='proposals/')),
            ],
        ),
        migrations.CreateModel(
            name='PrepSocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_select', models.CharField(choices=[('select', 'Select'), ('twitter', 'Twitter'), ('telegram', 'Telegram')], default='Select', max_length=20)),
                ('link', models.CharField(default='', max_length=500)),
                ('prep', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social', to='core.Prep')),
            ],
        ),
        migrations.CreateModel(
            name='PrepTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('name', models.CharField(max_length=100)),
                ('background', models.CharField(default='', max_length=2000)),
                ('prep', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team', to='core.Prep')),
            ],
        ),
    ]
