# Generated by Django 2.1.4 on 2018-12-13 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_prep_server_location_latlong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prepsocial',
            name='link',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='prepsocial',
            name='social_select',
            field=models.CharField(choices=[('select', 'Select'), ('twitter', 'Twitter'), ('telegram', 'Telegram')], default='Select', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='prepteam',
            name='background',
            field=models.CharField(default='', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='prepteam',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
