# Generated by Django 2.1.4 on 2018-12-17 02:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181213_0517'),
    ]

    operations = [
        migrations.AddField(
            model_name='prep',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prep',
            name='display',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='prep',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='prep',
            name='logo',
            field=models.ImageField(default='preview.jpg', upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='prepsocial',
            name='link',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='prepsocial',
            name='social_select',
            field=models.CharField(choices=[('select', 'Select Network'), ('website', 'Website'), ('youtube', 'YouTube'), ('medium', 'Medium'), ('twitter', 'Twitter'), ('telegram', 'Telegram'), ('slack', 'Slack'), ('reddit', 'Reddit'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('other', 'Other')], default='Select', max_length=20, null=True),
        ),
    ]
