# Generated by Django 2.1.4 on 2018-12-20 08:17

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20181217_0200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prep',
            name='proposal',
        ),
        migrations.AddField(
            model_name='prep',
            name='proposal_rich',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
