# Generated by Django 2.1.4 on 2019-01-09 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20181220_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prep',
            name='introduction',
            field=models.CharField(blank=True, default='', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='prep',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prep',
            name='logo',
            field=models.ImageField(blank=True, default='preview.jpg', null=True, upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='prep',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prep',
            name='server_location',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prep',
            name='server_location_latlong',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='prep',
            name='server_spec',
            field=models.CharField(blank=True, default='', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='prep',
            name='server_type',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
