# Generated by Django 2.1.4 on 2019-01-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190110_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_image',
            field=models.ImageField(blank=True, default='news/preview.jpg', null=True, upload_to='news/'),
        ),
    ]
