# Generated by Django 2.1.4 on 2019-02-12 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190110_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prepsocial',
            name='link',
            field=models.URLField(blank=True, default='', max_length=500, null=True),
        ),
    ]
