# Generated by Django 2.1.4 on 2019-02-18 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190212_0700'),
        ('core', '0010_news_news_link_kr'),
    ]

    operations = [
    ]
