# Generated by Django 2.1.4 on 2019-06-24 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_merge_20190218_0356'),
    ]

    operations = [
        migrations.AddField(
            model_name='prep',
            name='self_intro_video',
            field=models.URLField(blank=True, default='', max_length=500, null=True),
        ),
    ]
