# Generated by Django 2.1.4 on 2019-07-18 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_prep_self_intro_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prep',
            name='introduction',
            field=models.TextField(blank=True, default='', max_length=2000, null=True),
        ),
    ]
